site_name: ELB Best Practices Guides
repo_name: "aws/aws-elb-best-practices"
repo_url: "https://github.com/aws/aws-elb-best-practices"
docs_dir: "content"

theme:
  name: material
  features:
    - header.autohide
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  logo: ./images/elb-icon-large.png
  favicon: ./images/elb-icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: grey
      # accent: indigo
      toggle:
        icon: material/brightness-7
        name: switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: switch to light mode
    

nav:
  - Home: index.md
  - Security: 
    - Home: security/index.md
    - Data Protection: security/data_protection.md
    - Incident Response: security/incident_response.md
    - Infrastructure Protection: security/infrastructure_protection.md
    - Security Assurance: security/security_assurance.md
    - Vulnerability Management: security/vulnerability_management.md
  - Reliability:
    - Home: reliability/index.md
    - Failure Management: reliability/failure_management.md
    - Workload Architecture: reliability/workload_architecture.md
  - Checklist: checklist.md
  - Bookmarks: bookmarks.md


plugins: 
    - search
markdown_extensions:
    - attr_list
    - abbr
    - admonition
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.snippets:
        check_paths: true
        base_path:
        - content/src/markdown/.snippets
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
extra:
  analytics:
    provider: google
    property: G-RWH7DVZ8QV